=== RaphaelJ/Cours-3eme-ann-e/XML/examples/dtd/advertisements_ent.dtd
<!ENTITY % common_content "address, rooms, bathrooms">

<!ENTITY % rent_price "rent">
<!ENTITY % sale_price "sale">

<!ENTITY % studio_price "%rent_price;">
<!ENTITY % apartment_price "%rent_price;">
<!ENTITY % house_price "%sale_price;">

<!ENTITY % extra_house "">

<!ELEMENT advertisements (studio | apartment | house)*>
<!ELEMENT studio (%common_content;, %studio_price;)>
<!ELEMENT apartment (%common_content;, %apartment_price;)>
<!ELEMENT house (%common_content;, %house_price;, garden %extra_house;)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT rooms (#PCDATA)>
<!ELEMENT bathrooms (#PCDATA)>
<!ELEMENT rent (#PCDATA)>
<!ATTLIST rent charges (included | not_included) #REQUIRED>
<!ELEMENT sale (#PCDATA)>
<!ELEMENT garden EMPTY>
<!ATTLIST garden area CDATA #REQUIRED>

=== RaphaelJ/Cours-3eme-ann-e/XML/examples/dtd/advertisements_ent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE advertisements SYSTEM "advertisements_ent.dtd" [
	<!ELEMENT garage (#PCDATA)>
	<!ENTITY % extra_house ",garage?">
]>
<advertisements>
	<studio>
		<address>Rue Saint-Paul 52 4000 Liège</address>
		<rooms>1</rooms>
		<bathrooms>1</bathrooms>
		<rent charges="included">250</rent>
	</studio>
	<apartment>
		<address>Rue de la Cathédrale 13 4000 Liège</address>
		<rooms>2</rooms>
		<bathrooms>1</bathrooms>
		<rent charges="not_included">500</rent>
	</apartment>
	<house>
		<address>Rhode-Saint-Genèse</address>
		<rooms>4</rooms>
		<bathrooms>2</bathrooms>
		<sale>750000</sale>
		<garden area="300"/>
	</house>
	<house>
		<address>Linkebeek</address>
		<rooms>3</rooms>
		<bathrooms>1</bathrooms>
		<sale>500000</sale>
		<garden area="100"/>
		<garage>2</garage>
	</house>
</advertisements>
