=== RaphaelJ/Cours-3eme-ann-e/XML/examples/dtd/names.dtd
<!ELEMENT names (name*)>
<!ELEMENT name (last_name | (first_name, ((middle_name+, last_name) | last_name?)))>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>

=== RaphaelJ/Cours-3eme-ann-e/XML/examples/dtd/names.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE names SYSTEM "names.dtd" [
]>
<names>
    <name>
        <last_name>Kennedy</last_name>
    </name>
    <name>
        <first_name>Robert</first_name>
    </name>
    <name>
        <first_name>Robert</first_name>
        <middle_name>Jr.</middle_name>
        <middle_name>Mc.</middle_name>
        <last_name>Kennedy</last_name>
    </name>
    <name>
        <first_name>Robert</first_name>
        <last_name>Jr.</last_name>
    </name>
</names>
