=== RaphaelJ/Cours-3eme-ann-e/XML/XSLT-examples/XSLT2/books.dtd
<!ELEMENT title (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT author (firstname, lastname)>
<!ELEMENT book (title, author+, publisher?, edition?, pages?)>
<!ATTLIST book isbn CDATA #REQUIRED>
<!ELEMENT books (book*)>

=== RaphaelJ/Cours-3eme-ann-e/XML/XSLT-examples/XSLT2/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xml" href="books4.xslt"?>
<!DOCTYPE books SYSTEM "books.dtd">
<books>
	<book isbn="0-596-00197-5">
		<title>Java &amp; XML</title>
		<author>
			<firstname>Brett</firstname>
			<lastname>McLaughlin</lastname>
		</author>
		<publisher>O'Reilly</publisher>
		<edition>2nd</edition>
	</book>
	<book isbn="0-262-06217-8">
		<title>Essentials of Programming Languages</title>
		<author>
			<firstname>Daniel</firstname>
			<lastname>P. Friedman</lastname>
		</author>
		<author>
			<firstname>Mitchell</firstname>
			<lastname>Wand</lastname>
		</author>
		<author>
			<firstname>Christopher</firstname>
			<lastname>T. Haynes</lastname>
		</author>
		<edition>2nd</edition>
	</book>
</books>
