=== RaphaelJ/Cours-3eme-ann-e/XML/examples/ns/book_default.dtd
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT author (firstname, lastname)>
<!ELEMENT book (isbn, title, author+, publisher, edition)>
<!ATTLIST book
	added_at CDATA #REQUIRED
	xmlns CDATA #FIXED "http://cours.khi.be/ns/book">

=== RaphaelJ/Cours-3eme-ann-e/XML/examples/ns/book_default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book_default.dtd">
<book xmlns="http://cours.khi.be/ns/book" added_at="2011/07/15 15:02">
	<isbn>0-596-00197-5</isbn>
	<title>Java &amp; XML</title>
	<author>
		<firstname>Brett</firstname>
		<lastname>McLaughlin</lastname>
	</author>
	<publisher>O'Reilly</publisher>
	<edition>2nd</edition>
</book>
